JeoMeChu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path 
from . import views

app_name = 'articles'
urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
  path('<int:pk>/like/', views.like, name='like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField()
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
                            
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='images/', blank=True,
                            processors=[ResizeToFill(1200, 960)],
                            format='JPEG',
                            options={'quality': 80})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('last_name', 'email', )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.

# 로그인
def signup(request):
    if request.method == 'POST':
        signup_form = CustomUserCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        signup_form = CustomUserCreationForm()

    context = {
        'signup_form' : signup_form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        login_form = AuthenticationForm()

    context = {
        'login_form' : login_form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    messages.warning(request, '로그아웃 하였습니다.')
    return redirect('articles:index')

def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)
    
@login_required
def update(request):
    if request.method == 'POST':
        update_form = CustomUserChangeForm(request.POST, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        update_form = CustomUserChangeForm(instance=request.user)
    context = {
        'update_form': update_form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('accounts:detail', pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect('accounts:detail', pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <h2 class="py-2 my-2">{{ user.username }}님의 프로필</h2>
      {% if request.user == user %}
        <a href="{% url 'accounts:update' %}" class="btn btn-primary">
          프로필 수정
        </a>
      {% endif %}
      {% if request.user != user %}
        <a href="{% url 'accounts:follow' user.pk %}" class="btn btn-primary">
          {% if request.user in user.followers.all %}
            팔로우 취소
          {% else %}
            팔로우
          {% endif %}
        </a>
      {% endif %}
      <hr>
      <p>E-mail :
        {{ user.email }}</p>
      <hr>
      <div class="d-flex justify-content-around text-center">
        <div>
          <h4>팔로잉</h4>
          <p>{{ user.followings.count }}</p>
        </div>
        <div>
          <h4>팔로우</h4>
          <p>{{ user.followers.count }}</p>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-12">
          <h4>작성한 글</h4>
          <p class="text-muted">{{ user.article_set.count }}개를 작성하였습니다.</p>
          {% for article in user.article_set.all %}
            <p>
              {{ forloop.counter }}
              <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
            </p>
          {% endfor %}
        </div>
        <hr>
        <div class="col-12">
          <h4>작성한 댓글</h4>
          <p class="text-muted">{{ user.comment_set.count }}개를 작성하였습니다.</p>
          {% for comment in user.comment_set.all %}
            <p>
              {{ forloop.counter }}
              <a href="{% url 'articles:detail' comment.article_id %}">{{ comment.content }}</a>
            </p>
          {% endfor %}
        </div>
        <hr>
        <div class="col-12">
          <h4>좋아요 누른 글</h4>
          <p class="text-muted">{{ user.like_articles.count }}개를 작성하였습니다.</p>
          {% for article in user.like_articles.all %}
            <p>
              {{ forloop.counter }}
              <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
            </p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <h1 class="my-3 py-3 text-center">로그인</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form login_form %}
        <div class="text-end">
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
          <button type='submit' class="btn btn-primary">로그인</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <h1 class="my-3 py-3 text-center">회원가입</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form signup_form %}
        <button type='submit' class="btn btn-primary float-end">회원가입</button>
      </form>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <h1 class="my-3 py-3 text-center">프로필 업데이트</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form update_form %}
        <button type='submit' class="btn btn-primary float-end">수정</button>
      </form>
    </div>
  </div>
{% endblock body %}