JeoMeChu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path 
from . import views

app_name = 'articles'
urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
  path('<int:pk>/like/', views.like, name='like'),
]

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField()
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
                            
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='images/', blank=True,
                            processors=[ResizeToFill(1200, 960)],
                            format='JPEG',
                            options={'quality': 80})

articles/forms.py
from django import forms
from .models import Article, Comment

GRADE_POINT_CHOICES = (
    ('1', 1),
    ('2', 2),
    ('3', 3),
    ('4', 4),
    ('5', 5),
)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'grade', ]
        widgets = {
            'grade': forms.Select(choices=GRADE_POINT_CHOICES)
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment 
        fields = ['content', ]

articles/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_safe
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.core.paginator import Paginator

# Create your views here.

@require_safe
def index(request):
    page = request.GET.get('page', '1')
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles, 6)
    page_obj = paginator.get_page(page)
    context = {
        'articles': articles, 
        'articles_list' : page_obj,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user 
            article.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('articles:index')
    else: 
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context=context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': article.comment_set.all(),
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user: 
        if request.method == 'POST':
            article_form = ArticleForm(request.POST, request.FILES, instance=article)
            if article_form.is_valid():
                article_form.save()
                messages.success(request, '글이 수정되었습니다.')
                return redirect('articles:detail', article.pk)
        else:
            article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form
        }
        return render(request, 'articles/form.html', context)
    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('articles:detail', article.pk)

@login_required
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('articles:index')

@login_required
def comment_create(request, pk):
    print(request.POST)
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        context = {
            'content': comment.content,
            'userName': comment.user.username
        }
        return JsonResponse(context)

def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()

    return redirect('articles:detail', article_pk)

    

@login_required
def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.like_users.all(): 
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    context = {'isLiked': is_liked, 'likeCount': article.like_users.count()}
    return JsonResponse(context)

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <h2>{{ article.title }}</h2>
      <hr>
      <p>{{ article.content }}</p>
      <p>평점 |
        {{ article.grade }}</p>
      {% if request.user == article.user %}
        <a href="{% url 'articles:update' article.pk %}">수정하기</a>
        <a href="{% url 'articles:delete' article.pk %}">삭제하기</a>
      {% endif %}
      {% if request.user.is_authenticated %}
        {% if request.user in article.like_users.all %}
          <div class="text-center">
            <button class="btn btn-primary">
              <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart-fill"></i>
              <span id="like-count">{{ article.like_users.count }}</span>
            </button>
          </div>
        {% else %}
          <div class="text-center">
            <button class="btn btn-primary">
              <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart"></i>
              <span id="like-count">{{ article.like_users.count }}</span>
            </button>
          </div>
        {% endif %}
      {% endif %}
      <h5 class="my-3">댓글</h5>
      <hr>
      <div id="comments">
        {% for comment in comments %}
          <p>{{ comment.user.username }}
            |
            {{ comment.content }}
          </p>
          {% comment %} {% if request.user == comment.user %}
            <a href="{% url 'articles:comment_delete' article.pk comment.pk %}">삭제하기</a>
          {% endif %} {% endcomment %}
          <hr>
        {% endfor %}
      </div>
      {% if request.user.is_authenticated %}
        <div class="py-3">
          <form id="comment-form" data-article-id="{{ article.pk }}">
            {% csrf_token %}
            {% bootstrap_form comment_form layout='floating'%}
            <button type="submit" class="btn btn-primary">댓글 작성</button>
          </form>
        </div>
      {% endif %}
    </div>  
  </div>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const likeBtn = document.querySelector('#like-btn')
    likeBtn.addEventListener('click', function (event) {
      console.log(event.target.dataset)
      axios({method: 'get', url: `/articles/${event.target.dataset.articleId}/like/`}).then(response => {
        console.log(response)
        console.log(response.data)
        if (response.data.isLiked === true) {
          event
            .target
            .classList
            .add('bi-heart-fill')
          event
            .target
            .classList
            .remove('bi-heart')
        } else {
          event
            .target
            .classList
            .add('bi-heart')
          event
            .target
            .classList
            .remove('bi-heart-fill')
        }
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.likeCount
      })
    })
  </script>
  <script>
    const commentForm = document.querySelector('#comment-form')
    const csrftoken = document
      .querySelector('[name=csrfmiddlewaretoken]')
      .value
      commentForm
      .addEventListener('submit', function (event) {
        event.preventDefault();
        axios({
          method: 'post',
          url: `/articles/${event.target.dataset.articleId}/comments/`,
          headers: {
            'X-CSRFToken': csrftoken
          },
          data: new FormData(commentForm)
        }).then(response => {
          console.log(response.data)
          const comments = document.querySelector('#comments')
          const p = document.createElement('p')
          p.innerText = `${response.data.userName} | ${response.data.content}`
          const hr = document.createElement('hr')
          comments.append(p, hr)
          commentForm.reset()
        })
      })
  </script>
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 30rem;">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form article_form %}
        <button type='submit' class="btn btn-primary float-end">작성</button>
      </form>
    </div>
  </div>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <style>
    .bg-img {
      background-image: url({% static 'articles/cf3c5eef-de48-41e4-bdc8-abad850e4bf1.jpg' %});
      width: 100%;
      height: 530px;
      background-size: cover;
    }

    .card {
      margin-bottom: 2rem;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="bg-img p-0"></div>
{% endblock %}

{% block section %}
  <div class="my-3 d-flex align-items-center justify-content-between">
    <h2 class="fw-bold" style="color: #f96e46"># 맛집 리스트</h2>
    <a href="#" class="text-muted text-decoration-none fs-5">더보기</a>
  </div>
  <div class="row">
    {% for article in articles_list %}
      <div class="col-3">
        <div class="card" style="width: 18rem;">
          {% if article.image %}
            <img src="{{ article.image.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top" alt="...">
          {% endif %}
          <div class="card-body">
            <a href="{% url 'articles:detail' article.pk %}">
              <h3 class=" card-text">{{ article.title }}</h3>
            </a>
            <p class="card-text">{{ article.content }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}