JeoMeChu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path 
from . import views

app_name = 'articles'
urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
  path('<int:pk>/like/', views.like, name='like'),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JeoMechu</title>
    {% block css %}{% endblock %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% comment %} <style>
      body {
        background-color: #fcecf4;
      }
    </style> {% endcomment %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg p-0 shadow-sm sticky-top" style="background-color: #fcecf4;">
      <div class="container-fluid">
        <a class="navbar-brand p-0" href="{% url 'articles:index' %}">
          <img src="{% static 'articles/logo.jpg'%}" style="width: 100px; height: 45px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <form onsubmit="searchPlaces(); return false;">
            키워드 : <input type="text" id="keyword" size="15">
            <button type="submit">검색하기</button>
          </form>
          <ul class=" navbar-nav ms-auto p-0 m-0">
            <li class="nav-item">
              <a class="nav-link fw-bold" aria-current="page" href="#">맛집 리스트</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link fw-bold" href="{% url 'articles:create' %}">맛집 등록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link fw-bold" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
              <a class="nav-link fw-bold" href="{% url 'accounts:detail' user.pk %}">내 정보</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link fw-bold" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block body %}{% endblock %}
    <section class="container">
      {% block section %}{% endblock %}
    </section>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>